### ISSUE TITLE
Double check confirmatory analysis R codes

### ISSUE THREAD

**Issue by angelinetsui** [manybabies/mb1-cdi-followup#12]
@christinabergmann , Hello Christina, I have finalized the confirmatory analysis. Can you please take a look at 03_confirmatory_analysis.Rmd (I.e. I also knitted the file to 03_confirmatory_analysis.html for convenience)? I am happy to answer any questions if you see something wrong or any way to improve the script.

@melsod , Hi Melanie, you are tagged here for communication purpose! Thanks

**Comment by christinabergmann** [comment]
Hi, I went ahead and started at preprocessing to better understand the data. A few observations:
1) 01_read_and_merge.Rmd Chunk cdi-check. I get quite a few duplicates (n=47). I only see fixes for 4, what happened to the rest?
2) Wouldn't it be better to pull the MB1 data directly from the repo? 

Now on to the actual document:
1) Would it be possible to indicate instrument size in the lab/vocabulary plot? Otherwise it is difficult to compare scores across labs. Or use proportions? (I am of course not aware of any discussions you probably had on this question, so apologies).
3) I agree with Melanie on the simple correlations. Either look at growth (i.e. difference, probably with quite some data loss), or do separate analyses by age. 
4) The correlation / scatter plots would need titles or so that indicate the sample, if possible.
5) There is a salient floor effect in the younger NAE sample for CDI scores, which makes me a bit queasy about using those scores at all without transformation, just a note. For modelling, it might also be useful to consider the fact that data are censored. (I haven't read the manuscript yet, this note is also so I remember to look for a mention of the floor effect). 
6) Note that I don't see the output of the power analyses in the html

Nothing else stood out to me.

**Comment by angelinetsui** [comment]
Hi Christina,

Thanks for double checking the codes. 

1) I need help with 01.Rmd, which line you find duplicates? Did I miss anything? Note that I am not the person who worked on the scripts before, so I am not as familiar as Arthur in these files?

2) We can definitely add instrument size in the vocabulary plot? can you indicate which plot you are referring?

3) okay. I think we can separate the correlation plot by age? 

4) will add titles about sample size

5) ummm, I will need to look into the residuals of the analyses sometime later to see if transformation is necessary

6) I deliberately "turn off" the power analyses as it generated a lot of singularity messages. But all the codes were there if people are interested in running the power analyses. We are not including this post-hoc power analyses in the RR as well

**Comment by christinabergmann** [comment]
Ah, that was fast:
 
1. https://github.com/manybabies/mb1-cdi-followup/blob/master/01_read_and_merge.Rmd --> The chunk is called cdi_check, sorry for the typo. Line 69 onwards.
2. Lin 167 onwards. 
3. I think you also compute these correlations with both age groups merged in one. See Melanie's note line 184
4. Oh, I mean sample, not sample size. I.e. NAE vs UK
5. Yes, although I just realized that CDI scores predict IDS pref, not vice versa, right? So it should not be a big problem. But diagnostics would actually be great. Do you have them somewhere?
6. Ah, might be nice to add that to the doc then? Or I missed it, in that case sorry, of course!

**Comment by angelinetsui** [comment]
@christinabergmann , @melsod 

I have checked 01_read_and_merge.Rmd. I think the duplicates (i.e., duplicates that have the exact age and cdi scores from the same participants) have been solved by the code "unique" at line 94 for the chunk "cdi_fix_babylablmu".

Only one lab (Brooke-mb46) has collected two different sets of cdi from the same participants at 24 months at two different times, one at 22 months and 24 months. So the data at 22 months was deleted at 02_exclusion_and_new_variable.Rmd. So we are good. Nothing needs to be changed for data entry

**Comment by christinabergmann** [comment]
Ah, excellent, thanks for confirming.

**Comment by melsod** [comment]
I added a note into the manuscript that the analysis is a bit funky because of the age effect (I didn't phrase it that way of course). We could run separate analyses by age, I guess, but it seems terribly redundant with the main analysis (I'm regretting the planned Pearson correlation in the first place). So I'm tempted to just report it, acknowledge the problem with it, and move on...

**Comment by melsod** [comment]
The UK Pearson correlation issue has been resolved. Is there anything else in this issue that is still outstanding?

**Comment by melsod** [comment]
@christinabergmann @angelinetsui Can I close this issue now?

**Comment by angelinetsui** [comment]
I think we can close this issue. 

@christinabergmann , are you good with this as well?

**Comment by angelinetsui** [comment]
I think we can close this issues, after Joselin helps me to double check the numbers after I center the IDS variable next weekend

**Comment by angelinetsui** [comment]
I also removed Christina here because it is no longer a task that assigned to her as well. Thanks

@Joscelinrocha
