### ISSUE TITLE
03a line 508

### ISSUE THREAD

**Issue by melsod** [manybabies/mb1-cdi-followup#26]
I am getting an error related to furrr:

Quitting from lines 508-528 (03a_confirmatory_analysis.Rmd) 
Error in lme.formula(CDI.prop ~ CDI.z_age_months + language_zone + gender +  : 
  nlminb problem, convergence error code = 1
  message = iteration limit reached without convergence (10)
Calls: <Anonymous> ... withVisible -> eval -> eval -> <Anonymous> -> lme.formula
In addition: Warning messages:
1: package 'future' was built under R version 4.1.2 
2: In supportsMulticoreAndRStudio(...) :
  [ONE-TIME WARNING] Forked processing ('multicore') is not supported when running R from RStudio because it is considered unstable. For more details, how to control forked processing or not, and how to silence this warning in future R sessions, see ?parallelly::supportsMulticore
3: package 'furrr' was built under R version 4.1.2 
Execution halted

**Comment by angelinetsui** [comment]
@melsod , I looked into the issues, I found that the UK and combined models needed to trim more. I do not know why it was not a problem in 2021 when I ran the models, but right now, both models (except the NAE model) needed to remove more random effects to reach convergence. I have ensured that this is not due to any updates in my lme4 package. 

I have sequentially removed (1| labid) in the UK model and also the CDI.z_age_months random effect from (1| labid). Now the file can be knitted. 

If time permits, I will look into the coding about "checking assumptions" of each model (esp for the autocorrections part). but because assumptions checking is not part of our pre-registrated methods in RR Stage 1, I will focus on my time on other parts, such as exploratory analysis and etc

**Comment by angelinetsui** [comment]
@melsod : Re the error: it was related to the nlme code not being able to execute (for autocorrelation lme4 assumption checking) if the combined model had singularity problem (this problem exists after some changes in the data). After I have solved the problem of convergence (i.e., singularity), the nlme code problem is solved

**Comment by Joscelinrocha** [comment]
Last time we ran it, there were no more errors. Should this issue be closed?
