### ISSUE TITLE
04_compute_percentiles_mb_cdi

### ISSUE THREAD

**Issue by angelinetsui** [manybabies/mb1-cdi-followup#30]
@munozalvalu 

I am reviewing 04 rmd, a few things:

1) from line 41 to 95, where are the following files: korean.txt, oxford.txt, web_cdi.txt, norwegian.txt, german.txt, french.txt

2) for line 137: why the perc_CDI1_prod$Age needs to +15? I have the same question for line 139

3) For the giant function (btw, this is pretty cool) from line 101 to 186: I think we need more descriptions of what the line is doing and why they need to do it. For example, the age + 15 lines, or the floor(perc/2) line. What are these lines doing? Why it is needed? We need clear documentation to explain how we compute the percentile in the Rmd because the reviewers will probably go through the code line by line and see how this aligns with our writing in the RR Stage 2

**Comment by munozalvalu** [comment]
Hi @angelinetsui,

1. From the main folder you can use this path to find those documents: "mb1-cdi-followup\data\cdi_percentile"
2. The idea behind this is that when countries collect their norming data they often use age in months for the infants to define how old they are. The issue is that age in month can either be defined as centered around the month-anniversary of the baby (15month-old babies would include 14month-olds+15day to 15months-old+15day) or in terms of full months (15months-old babies would include 15m00d to 15m30d). The 15d correction makes the mapping from one to the other.
3. I'm updating some of the descriptions. Though I'm not sure how much I should add in the code about the 15 day correction. Please feel free to update this as you see would befit the reviewers.

**Comment by munozalvalu** [comment]
I've updated some of the descriptions now. Please let me know if this is still unclear.
