### ISSUE TITLE
col_types in 02_file 

### ISSUE THREAD

**Issue by mohmdsh** [manybabies/mb1-cdi-followup#38]
It seems that the new merge has caused a change in our online image, that we're working on. Since yesterday, we got a message of an error from  02_exclusion line 29-57

On the project virtual image, my team and I get the following:
Error in vroom::vroom(file, delim = ",", col_names = col_names, col_types = col_types, : object 'col_types' not found

* Virtual image  (a copy of the project) uses R.4.2.1 with exact version provided in `sessioninfo` files

On my local machine, I got the following 

 Error in as.col_spec(col_types) : object 'col_types' not found

* My virtual image R 4.0.3

- We think that col_names should be FALSE, otherwise col_types is not recycled.

If you don't get a similar error, let me know so we modify our virtual copy and reconfigure it agin.

**Comment by melsod** [comment]
Thanks! This is an error on my end too. @Joscelinrocha  - if I delete the below code, it runs fine. I think what is going wrong is that you've separated the place where col_types is called from where it is defined into different code blocks. I didn't want to fix it myself because I know you're trying to match a particular formatting standard. I think if you just move them into the same code block it should be fine though.

https://github.com/manybabies/mb1-cdi-followup/blob/be5198fb8c8d62dd80db6514efbf6a7c5b7bb8b8/02_exclusion_and_new_variables.Rmd#L57-L60
