### ISSUE TITLE
infantlanglabutk subids

### ISSUE THREAD

**Issue by respatte** [manybabies/mb1-cdi-followup#5]
The following subids in the CDI data don't have matches in the initial IDS dataset:

```
infantlanglabutk:mb1r131fs3
infantlanglabutk:mb1r144fs8
```

There are 20 subids from the IDS that have no counterpart in the CDI data (see file [`/data/subids/infantlanglabutk.csv`](https://github.com/manybabies/mb1-cdi-followup/blob/master/data/subids/infantlanglabutk.csv)). The above subids where either not included in the initial IDS dataset for some reason, or are typos and should correspond to one of the available subids from the IDS dataset.

**Comment by melsod** [comment]
Response from the lab: The files for the 2 IDs were corrupted and we were unable to extract data. I am not sure why they aren’t in the MB1 dataset as they are listed on our document with error.

My add-on: It's possible that they are among the unmatched IDS subids - I remember there were a lot of matching issues on this one. But I don't think it's worth investigating further since we know they are discards anyway.

**Comment by respatte** [comment]
Strange indeed but at least discarding them is easy enough!
