### ISSUE TITLE
infantcogubc duplicate entry

### ISSUE THREAD

**Issue by respatte** [manybabies/mb1-cdi-followup#7]
We have two CDI score entries for participant `infantcogubc:tp13` at 24 months, and neither of those is flagged as an error. It might be that there is a subid typo for one of those, or that the parent filled in the webcdi twice. Either way, we need to fix this, either correcting the typo or selecting one of the two based on some objective criteria if possible.

**Comment by melsod** [comment]
response from lab: TP13 had, indeed, done the survey at 24 months twice. They first did it on July 11th, 2019 and they did it another time on August 9th, 2019. I believe there was an error on our end and we seemed to have sent out the link to them twice. Perhaps one of the RAs did not make a note in our records when we sent it to them the first time. Sorry about that! 


Also, the first one they did (July 11th, 2019) is the one in which "vocab_nwords" is 289.

**Comment by respatte** [comment]
Alright, both entries have the same age in days, so it is possible the parents re-filled the questionnaire "retrospectively" and entered the same age day in August as in July, but misremembering what their child's vocabulary was like in July, or something like that.

For now I'm excluding the August entry, but can we double check with the lab that the age is correct (744 days old on the 11th of July 2019).

**Comment by melsod** [comment]
New response from the lab: So I did a bit more digging in our records and actually it seems that that survey the family did on July 11th, 2019 was only half completed and should not have been included in the data set. This makes sense as we sent it to them again two weeks later and they did it on August 9th, 2019. Since the survey was completed on August 9th, 2019, the child's age in days was actually 758 days. Please use the information from the row of TP13 which has "vocab_nwords" as 470.
